auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095 # Porta para gRPC, necessária para comunicação interna

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  max_transfer_retries: 0
  wal:
    dir: /loki/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks # Onde os chunks de log são armazenados

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 dias de idade máxima para amostras a serem rejeitadas
  max_query_lookback: 168h # Máximo período para consultas (7 dias)

chunk_store_config:
  max_look_back_period: 0s # Pode ser ajustado para um período maior se precisar consultar logs muito antigos

# Esta seção 'ruler' não é estritamente necessária para logs, mas é bom ter um placeholder
ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost
  ring:
    kvstore:
      store: inmemory